# ---- Master variables (replaces the "Master variables" block in the bash script) ----
base_input_dir: "/media/Share2/benchmarking_experiment_Akoya/run1"
base_output_dir: "/home/luna.kuleuven.be/u0172795/Documents/DISSCOvery"
base_input_meta: "/home/luna.kuleuven.be/u0172795/Documents/DISSCOvery/experimental_design"
project_name: "test_AKOYA_revission"
scripts: "/home/luna.kuleuven.be/u0172795/Documents/DISSCOvery/code"
seed: '1234'
slide_id: 'test'
user_id: 'KN'
project_id: 'BM'

# 01
# Deafult number of workers for a single process
# CHNAGE IT WITH CAUTION !!! 
# Snakemake run few processes at once. Depending on number of cores 
# assigned to snakemake it may exceed machine's computantional power
num_workers: "2"

# 02 FFC variables
ffc_only_dapi: True # Shoudl mask for Kask be fitted on DAPI channel? (strnolgy recommended)
technology: "AKOYA"
hs_pixel_size: "2.6" # Pixel size for FFC
n_cores_ffc: "4"
ffc_basic_n_fit_images: '100' # max tiles randomly sampled to fit the model
ffc_basic_device: 'cpu' # cuda', 'cpu', or 'none'
ffc_ref_channel: "DAPI" # Reference channel used for FFC, STS and AlignQC
ref_round: "R01" # Reference round used for FFC, STS, AlignQC and segmentation
ref_version: "V01" # Reference version used for FFC, STS and AlignQC

# 03-04 STS
pixel_input: "0.5"
pixel_output_sts: "2.6"
pixel_output_qc: "0.65"
sts_ref_channel: 'DAPI'
sts_only_dapi: True
sts_reg_zscore: '20' # regsitraion z score for STS course registration

bool_t: "True"
bool_f: "False"

# 06 Split scenes
# Split scenes needs reference round and version for each slide to be specified before running the pipeline
reference_map:
  test: # slide name
    reference_round: "R01"
    reference_version: "V01"


# 09 Segmentation
conv_factor_seg: '2.321429' # Conversion factor (1 for MILAN 0.65/0.28 for COMET, 0.65/0.5 for AKOYA)
segmentation_model: 'stardist' # Segmentwtion model

# 10 FE
reference_round: "R01"

# 11 Cell identification
ci_node_id: "n01"
ci_version_id: "v01"
ci_child_id: "c01"
normalization_yes_or_no: '1' # Should data be normalized? 1: yes, 0: no
normalization_scope: 'sample' #sample or global, sample (default): z-score each marker per sample_id (slide+scene),
# the original behavior, global: z-score each marker across the whole dataset, with no sample grouping.
sample_yes_or_no: '1' # Should only a sample of the data be used for clustering? 1: yes, 0: no
number_of_cells: '15000' # How many cell should be sampeld?
sample_seed: '1234' # Seed for sampling
phenotypic_markers_list: ['FOXP3', 'TIM3', 'CD56'] # markers for 1st level clustering

knn_n_neighbors: '25'
prediction_high_confidence: '0.80'
prediction_medium_confidence: '0.60'
generate_marker_plots: '1'
generate_spatial_plots: '1'
spatial_max_points.per_plot: '200000'